[[main]]
name = "Home"
url = "/"
weight = "5"
[[main]]
name = "Issues"
url = "categories"
weight = 20
[[main]]
name = "About Us"
url = "people"
weight = 30
[[main]]
name = "Fun Games"
url = "game"
weight = 60
