address_format = "en-us"
appointment_url = "https://calendly.com"
contact_links = []
date_format = "Jan 2, 2006"
day_night = true
description = "My research group description."
diagram = false
directions = "Enter Building 1 and take the stairs to Reception on Floor 2"
email = "brendon.wang@gmail.com"
font = "native"
font_size = "L"
highlight = false
local_business_type = ""
math = true
office_hours = ["9:00 to 17:00 Monday to Friday"]
org_name = ""
phone = "???-???-????"
plugins_js = []
privacy_pack = false
sharing = false
sharing_image = ""
site_type = "Organization"
theme = "TigerTimes"
time_format = "3:04 PM"
twitter = ""
[address]
city = "Stanford"
country = "United States"
country_code = "US"
postcode = "94305"
region = "CA"
street = "450 Serra Mall"
[avatar]
gravatar = false
shape = "circle"
[cms]
branch = "main"
local_backend = false
[comments]
provider = ""
[comments.commentable]
docs = true
page = true
post = true
project = true
publication = true
talk = true
[comments.commento]
url = ""
[comments.disqus]
shortname = ""
show_count = true
[coordinates]
latitude = "37.4275"
longitude = "-122.1697"
[copyright_license]
allow_commercial = false
allow_derivatives = false
enable = false
notice = "This work is licensed under {license}"
share_alike = true
[icon.pack]
ai = true
[main_menu]
align = "r"
enable = true
highlight_active_link = false
show_day_night = true
show_language = false
show_logo = true
show_search = true
[map]
api_key = ""
provider = "mapnik"
zoom = 15
[marketing]
google_analytics = ""
google_site_verification = ""
google_tag_manager = ""
[projects]
post_view = 2
publication_view = 2
talk_view = 2
[publications]
citation_style = "apa"
date_format = "January 2006"
[search]
provider = "wowchemy"
[search.algolia]
api_key = ""
app_id = ""
index_name = ""
show_logo = false
[show_related]
post = true
project = true
publication = true
talk = true
