---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: config
  label: Edit All
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Edit
  create: all
  match: "**/*"
  new_doc_ext: md
- type: document
  path: content/authors
  label: Edit
- type: directory
  path: config/_default/content
  label: Pages
  create: all
  match: "*"
upload_dir: ''
public_path: content/post/**/*
front_matter_path: content/post/**/*
use_front_matter_path: true
file_template: ":year:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
