---
label: hero.md
hide_body: false
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: light
  type: text
  config:
    required: false
  label: light
- name: primary
  type: color
  label: primary
  config:
    required: false
    color_format: Hex
- name: menu_primary
  type: color
  label: menu_primary
  config:
    required: false
    color_format: Hex
- name: menu_text
  type: color
  label: menu_Text
  config:
    required: false
    color_format: Hex
pages:
- data/theme/my_theme.toml.md
